### ISSUE TITLE
panic when finding a version fails

### ISSUE THREAD

**Issue by krishicks** [abennett/hashi-releases#1]
I tried finding nomad 0.10.2 and this is the result:

```
0.10.2 not found for nomad
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7a51bb]

goroutine 1 [running]:
main.(*IndexCommand).Run(0xc0002ad880, 0xc0000201a0, 0x1, 0x1, 0xc00036a7c0)
	/go/src/github.com/abennett/hashi-releases/releases.go:254 +0xdb
github.com/mitchellh/cli.(*CLI).Run(0xc0000c6000, 0xc000a80a80, 0xc000361da0, 0x0)
	/go/src/github.com/mitchellh/cli/cli.go:255 +0x1da
main.main()
	/go/src/github.com/abennett/hashi-releases/main.go:22 +0x127
```

It prints a legit error but also panics.

**Comment by krishicks** [comment]
Also, note that 0.10.2 is (was at time of the error) legitimately not available.

**Comment by abennett** [comment]
Fixed! Missed a simple return statement. Thanks for the issue!
